version: "3.7"

services:
    app:
        build: ./code
        env_file: 
            - config/app.env
        ports:
            - "3000:3000"
        working_dir: /app
        volumes:
            - type: bind
              source: ./code
              target: /app
            - type: bind
              source: ./data
              target: /data
        depends_on:
            - db
    playground:
        image: jupyter/base-notebook
        build: ./playground
        env_file:
            - config/app.env
        ports:
            - "127.0.0.1:8888:8888"
        volumes:
            - type: bind
              source: ./playground
              target: /analysis
            - type: bind
              source: ./code
              target: /app
            - type: bind
              source: ./data
              target: /data
    db:
        image: postgres:12-alpine
        env_file: 
            - config/primary_db.env
        ports:
            - "8000:5432"
        volumes:
            - type: volume
              source: news-db
              target: /var/lib/postgres
    test_db:
        image: postgres:12-alpine
        env_file:
            - config/test_db.env
        ports:
            - "8001:5433"
        volumes:
            - type: volume
              source: test-db
              target: /var/lib/tst_postgres
volumes:
    news-db:
    test-db: